#!/bin/busybox sh

/bin/busybox --install -s /bin

mkdir -p dev proc sys tmp
mount -t devtmpfs  devtmpfs  /dev
mount -t proc      proc      /proc
mount -t sysfs     sysfs     /sys
mount -t tmpfs     tmpfs     /tmp

for mod in $(cat usr/share/kernel-modules.lst); do
    modprobe $mod
done

udhcpc -v

setsid cttyhack sh
